name: 'Generate Assets'
description: 'Generate Minecraft default resourcepack assets.'
author: 'Mqxx'
branding:
  icon: 'folder'
  color: 'green'

inputs:
  version: 
    description: 'Minecraft version to generate assets for.'
    required: true

  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the assets.'
    required: false
    default: './default'

  api-url:
    description: 'URL to the Minecraft manifest API.'
    required: false
    default: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
  
  resources-url:
    description: 'URL to the Minecraft resources API.'
    required: false
    default: 'https://resources.download.minecraft.net'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_PATH: ${{ inputs.path }}
    INPUT_MANIFEST_API_URL: ${{ inputs.api-url }}
    INPUT_RESOURCES_API_URL: ${{ inputs.resources-url }}
