name: 'Test Action'
on:
  workflow_dispatch:
    inputs:
      download_retries:
        type: string
        description: 'How much times to retry a failed download.'
        required: false

  push:
    branches: ['main']

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: 'Test Generate Assets action'
    steps:
      - uses: actions/checkout@v4

      - name: 'Test'
        id: test
        uses: ./
        with:
          path: './default'
          version: 'latest-snapshot'
          parallel-downloads: 10
          download-retries: '${{ github.event.inputs.download_retries || 3 }}'
        
      - name: 'List failed downloads'
        run: |
          echo "Failed downloads: ${{ steps.test.outputs.failed-downloads }}"
          if [ "${{ steps.test.outputs.failed-downloads }}" != "[]" ]; then
            echo "Some downloads failed: ${{ steps.test.outputs.failed-downloads }}"
            exit 1
          fi
      
      - name: 'Upload generated assets'
        uses: actions/upload-artifact@v4
        with:
          name: 'default'
          path: './default'
          compression-level: 9
