name: 'Test Action'
on:
  push:
    branches: ['main']

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: 'Test Generate Assets action'
    steps:
      - uses: actions/checkout@v4

      - name: 'Test'
        uses: ./
        with:
          path: './default'
          version: '1.21.3'
          parallel-downloads: 10
      
      - name: 'Upload generated assets'
        uses: actions/upload-artifact@v4
        with:
          name: 'default'
          path: './default'
          compression-level: 9
