name: 'Test Action'
on:
  push:
    branches: ['main']

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: 'Test Generate Assets action'
    steps:
      - uses: actions/checkout@v4

      - name: 'Test'
        uses: ./
        with:
          version: '1.21.3'
